# Conductor Configuration File
# This file defines repositories managed by Conductor.

repositories:
  - name: repo1
    url: https://github.com/example/repo1.git
  - name: repo2
    url: https://github.com/example/repo2.git 