# Depsync Configuration File
# This file defines repositories managed by Depsync.

repositories:
  - https://github.com/example/repo1.git
  - https://github.com/example/repo2.git

git:
  author:
    name: "Depsync Bot"
    email: "depsync@example.com" 