name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run linter
    if: github.event_name == 'pull_request'
    runs-on: k8s-home-runners
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest
          verb: call
          args: lint --source-dir=.
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "tcp://dagger-engine.dagger.svc.cluster.local:8080"

  generate:
    name: Run code generation
    if: github.event_name == 'pull_request'
    runs-on: k8s-home-runners
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest
          verb: call
          args: generate --source-dir=.
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "tcp://dagger-engine.dagger.svc.cluster.local:8080"

  unit-tests:
    name: Run unit tests
    if: github.event_name == 'pull_request'
    needs: [lint, generate]
    runs-on: k8s-home-runners
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest
          verb: call
          args: unit-tests --source-dir=.
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "tcp://dagger-engine.dagger.svc.cluster.local:8080"

  integration-tests:
    name: Run integration tests
    if: github.event_name == 'pull_request'
    needs: [lint, generate, unit-tests]
    runs-on: k8s-home-runners
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          version: latest
          verb: call
          args: integration-tests --source-dir=. --github-token=env:GITHUB_TOKEN
        env:
          _EXPERIMENTAL_DAGGER_RUNNER_HOST: "tcp://dagger-engine.dagger.svc.cluster.local:8080"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 